### ISSUE TITLE
Event::once should have an implementation for FnOnce

### ISSUE THREAD

**Issue by mlthlschr** [specta-rs/tauri-specta#139]
Hi!

I don't know whether I am using the generated `Event` wrong or whether its a bug. 

When trying to send a Non-`Copy` object into the Callback of `once`, the compiler won't let me through as there is only implementation where the Callback is `Fn` (and thus the object must survive multiple calls). I would assume that there should be an implementation supporting `FnOnce`, which is what tauri itself does.

Below an example:

```rs
#[tauri::command]
#[specta::specta]
pub async fn hello_world(app: tauri::AppHandle) {
{
// does not compile
{
    let (tx, rx) = tokio::sync::oneshot::channel();

    events::HelloWorldEvent::once(&app, move |_e| {
        let _ = tx.send(true); // tx moved to here
    });

    rx.await;
}

// works
{
    let (tx, rx) = tokio::sync::oneshot::channel();

    app.once(events::HelloWorldEvent::NAME, move |_e| {
        let _ = tx.send(true); // tx moved to here
    });

    rx.await;
}
}
```

Thanks!

**Comment by oscartbeaumont** [comment]
This does look like a mistake, our definition of the functions should always match Tauri's as close as possible which as you've noted [takes an `FnOnce`](https://docs.rs/tauri/latest/tauri/struct.AppHandle.html#method.once) [not `Fn`.](https://docs.rs/tauri-specta/2.0.0-rc.20/tauri_specta/trait.Event.html#method.once).

Would be a fairly easy PR if you have time because I don't at the moment.
